version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      discovery.type: "single-node"
    volumes:
      - /var/elasticdata:/usr/share/elasticsearch/data
    deploy:
      restart_policy:
        delay: 2s
        max_attempts: 3
        window: 120s
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    ports:
      - "127.0.0.1:5601:5601"
    deploy:
      restart_policy:
        delay: 2s
        max_attempts: 3
        window: 120s
    networks:
      - elk
networks:
  elk:
