version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - "discovery.type=single-node"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx2048m"
      - "xpack.security.enabled=true"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    labels:
    - "co.elastic.logs/module=elasticsearch"
    deploy:
      restart_policy:
        delay: 2s
        max_attempts: 3
        window: 120s
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elasticsearch.rule=Host(`elasticsearch.ptrampert.com`)"
      - "traefik.http.routers.elasticsearch.entrypoints=websecure"
      - "traefik.http.routers.elasticsearch.tls.certresolver=letsencrypt"
      - "traefik.http.routers.elasticsearch.middlewares=auth"
      - "traefik.http.services.elasticsearch-service.loadbalancer.server.port=9200"
    networks:
      - traefik
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    labels:
    - "co.elastic.logs/module=kibana"
    deploy:
      restart_policy:
        delay: 2s
        max_attempts: 3
        window: 120s
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.rule=Host(`kibana.ptrampert.com`)"
      - "traefik.http.routers.kibana.entrypoints=websecure"
      - "traefik.http.routers.kibana.tls.certresolver=letsencrypt"
      - "traefik.http.routers.kibana.middlewares=auth"
      - "traefik.http.services.kibana-service.loadbalancer.server.port=5601"
    networks:
      - traefik
networks:
  traefik:
    external: true
    name: traefik
volumes:
  elasticsearch:
